package com.App.fullStack.pojos;

import lombok.*;

import java.io.Serializable;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "items")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Item implements Serializable {

    @Id
    private String Id; // Mandatory field, unique for business logic, not auto-generated by MongoDB
    private String itemId; // Mandatory field, unique for business logic, not auto-generated by MongoDB
    private String itemDescription;
    private String category;
    private String type;
    private ItemStatus status;// Available, Out of Stock, Backordered, Discontinued, On Hold, Pre-Order
    private String price;
    private boolean pickupAllowed;
    private boolean shippingAllowed;
    private boolean deliveryAllowed;

}
