package com.App.fullStack.pojos;
import lombok.*;
import java.io.Serializable;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "items")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Item implements Serializable{

    @Id
    private String id; // This will be the MongoDB document ID, typically of type String or ObjectId
    private String itemId; // Mandatory field, unique for business logic, not auto-generated by MongoDB
    private String itemDescription;
    private String category;
    private String type;
    private String status;
    private String price;
    private boolean pickupAllowed;
    private boolean shippingAllowed;
    private boolean deliveryAllowed;
}
